name: Build MoS2 Analyzer

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    working-directory: python_application

jobs:

  build-macos:

    runs-on: macos-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build app
      run: |
        pyinstaller gui.py \
        --windowed \
        --name MoS2_Analyzer \
        --add-data "models:models" \
        --add-data "data:data" \
        --add-data "analysis:analysis"

    - name: Zip application
      run: |
        cd dist
        zip -r MoS2_Analyzer_macOS.zip MoS2_Analyzer.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoS2_Analyzer_macOS
        path: python_application/dist/MoS2_Analyzer_macOS.zip